// Code generated by protoc-gen-go. DO NOT EDIT.
// source: laboratorio.proto

package laboratorio

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Paquete struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo                 string   `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor                string   `protobuf:"bytes,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tienda               string   `protobuf:"bytes,4,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Destino              string   `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Prioritario          string   `protobuf:"bytes,6,opt,name=prioritario,proto3" json:"prioritario,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paquete) Reset()         { *m = Paquete{} }
func (m *Paquete) String() string { return proto.CompactTextString(m) }
func (*Paquete) ProtoMessage()    {}
func (*Paquete) Descriptor() ([]byte, []int) {
	return fileDescriptor_9734614ddaf6515b, []int{0}
}

func (m *Paquete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paquete.Unmarshal(m, b)
}
func (m *Paquete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paquete.Marshal(b, m, deterministic)
}
func (m *Paquete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paquete.Merge(m, src)
}
func (m *Paquete) XXX_Size() int {
	return xxx_messageInfo_Paquete.Size(m)
}
func (m *Paquete) XXX_DiscardUnknown() {
	xxx_messageInfo_Paquete.DiscardUnknown(m)
}

var xxx_messageInfo_Paquete proto.InternalMessageInfo

func (m *Paquete) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Paquete) GetTipo() string {
	if m != nil {
		return m.Tipo
	}
	return ""
}

func (m *Paquete) GetValor() string {
	if m != nil {
		return m.Valor
	}
	return ""
}

func (m *Paquete) GetTienda() string {
	if m != nil {
		return m.Tienda
	}
	return ""
}

func (m *Paquete) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

func (m *Paquete) GetPrioritario() string {
	if m != nil {
		return m.Prioritario
	}
	return ""
}

type Paquetes struct {
	Paquete              []*Paquete `protobuf:"bytes,1,rep,name=paquete,proto3" json:"paquete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Paquetes) Reset()         { *m = Paquetes{} }
func (m *Paquetes) String() string { return proto.CompactTextString(m) }
func (*Paquetes) ProtoMessage()    {}
func (*Paquetes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9734614ddaf6515b, []int{1}
}

func (m *Paquetes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paquetes.Unmarshal(m, b)
}
func (m *Paquetes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paquetes.Marshal(b, m, deterministic)
}
func (m *Paquetes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paquetes.Merge(m, src)
}
func (m *Paquetes) XXX_Size() int {
	return xxx_messageInfo_Paquetes.Size(m)
}
func (m *Paquetes) XXX_DiscardUnknown() {
	xxx_messageInfo_Paquetes.DiscardUnknown(m)
}

var xxx_messageInfo_Paquetes proto.InternalMessageInfo

func (m *Paquetes) GetPaquete() []*Paquete {
	if m != nil {
		return m.Paquete
	}
	return nil
}

type Respuesta struct {
	Envio                string   `protobuf:"bytes,1,opt,name=envio,proto3" json:"envio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Respuesta) Reset()         { *m = Respuesta{} }
func (m *Respuesta) String() string { return proto.CompactTextString(m) }
func (*Respuesta) ProtoMessage()    {}
func (*Respuesta) Descriptor() ([]byte, []int) {
	return fileDescriptor_9734614ddaf6515b, []int{2}
}

func (m *Respuesta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Respuesta.Unmarshal(m, b)
}
func (m *Respuesta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Respuesta.Marshal(b, m, deterministic)
}
func (m *Respuesta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Respuesta.Merge(m, src)
}
func (m *Respuesta) XXX_Size() int {
	return xxx_messageInfo_Respuesta.Size(m)
}
func (m *Respuesta) XXX_DiscardUnknown() {
	xxx_messageInfo_Respuesta.DiscardUnknown(m)
}

var xxx_messageInfo_Respuesta proto.InternalMessageInfo

func (m *Respuesta) GetEnvio() string {
	if m != nil {
		return m.Envio
	}
	return ""
}

type Estado struct {
	Estado               string   `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Estado) Reset()         { *m = Estado{} }
func (m *Estado) String() string { return proto.CompactTextString(m) }
func (*Estado) ProtoMessage()    {}
func (*Estado) Descriptor() ([]byte, []int) {
	return fileDescriptor_9734614ddaf6515b, []int{3}
}

func (m *Estado) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Estado.Unmarshal(m, b)
}
func (m *Estado) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Estado.Marshal(b, m, deterministic)
}
func (m *Estado) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Estado.Merge(m, src)
}
func (m *Estado) XXX_Size() int {
	return xxx_messageInfo_Estado.Size(m)
}
func (m *Estado) XXX_DiscardUnknown() {
	xxx_messageInfo_Estado.DiscardUnknown(m)
}

var xxx_messageInfo_Estado proto.InternalMessageInfo

func (m *Estado) GetEstado() string {
	if m != nil {
		return m.Estado
	}
	return ""
}

type EstadoCamion struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo                 string               `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor                int32                `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen               string               `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino              string               `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Intentos             int32                `protobuf:"varint,6,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Fecha                *timestamp.Timestamp `protobuf:"bytes,7,opt,name=fecha,proto3" json:"fecha,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EstadoCamion) Reset()         { *m = EstadoCamion{} }
func (m *EstadoCamion) String() string { return proto.CompactTextString(m) }
func (*EstadoCamion) ProtoMessage()    {}
func (*EstadoCamion) Descriptor() ([]byte, []int) {
	return fileDescriptor_9734614ddaf6515b, []int{4}
}

func (m *EstadoCamion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstadoCamion.Unmarshal(m, b)
}
func (m *EstadoCamion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstadoCamion.Marshal(b, m, deterministic)
}
func (m *EstadoCamion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstadoCamion.Merge(m, src)
}
func (m *EstadoCamion) XXX_Size() int {
	return xxx_messageInfo_EstadoCamion.Size(m)
}
func (m *EstadoCamion) XXX_DiscardUnknown() {
	xxx_messageInfo_EstadoCamion.DiscardUnknown(m)
}

var xxx_messageInfo_EstadoCamion proto.InternalMessageInfo

func (m *EstadoCamion) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EstadoCamion) GetTipo() string {
	if m != nil {
		return m.Tipo
	}
	return ""
}

func (m *EstadoCamion) GetValor() int32 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *EstadoCamion) GetOrigen() string {
	if m != nil {
		return m.Origen
	}
	return ""
}

func (m *EstadoCamion) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

func (m *EstadoCamion) GetIntentos() int32 {
	if m != nil {
		return m.Intentos
	}
	return 0
}

func (m *EstadoCamion) GetFecha() *timestamp.Timestamp {
	if m != nil {
		return m.Fecha
	}
	return nil
}

func init() {
	proto.RegisterType((*Paquete)(nil), "Paquete")
	proto.RegisterType((*Paquetes)(nil), "Paquetes")
	proto.RegisterType((*Respuesta)(nil), "Respuesta")
	proto.RegisterType((*Estado)(nil), "Estado")
	proto.RegisterType((*EstadoCamion)(nil), "EstadoCamion")
}

func init() {
	proto.RegisterFile("laboratorio.proto", fileDescriptor_9734614ddaf6515b)
}

var fileDescriptor_9734614ddaf6515b = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x95, 0xb6, 0x49, 0xda, 0x29, 0x05, 0x61, 0x21, 0x64, 0x65, 0x43, 0xc8, 0xaa, 0x0b,
	0xe4, 0xa2, 0x72, 0x04, 0x54, 0xc1, 0x82, 0x05, 0x0a, 0x5c, 0xc0, 0x25, 0x6e, 0xb0, 0x94, 0xd8,
	0x21, 0x71, 0xba, 0xe7, 0x14, 0x5c, 0x89, 0x63, 0xe1, 0xd8, 0x4e, 0xc8, 0x0a, 0x89, 0x55, 0xe6,
	0xcf, 0x1f, 0x39, 0x7f, 0xde, 0xc0, 0x79, 0x41, 0xf7, 0xb2, 0xa6, 0x4a, 0xd6, 0x5c, 0x92, 0xaa,
	0x96, 0x4a, 0x46, 0x57, 0xb9, 0x94, 0x79, 0xc1, 0x36, 0x46, 0xed, 0xdb, 0xc3, 0x46, 0xf1, 0x92,
	0x35, 0x8a, 0x96, 0x95, 0x1d, 0x48, 0xbe, 0x3c, 0x08, 0x9f, 0xe9, 0x47, 0xcb, 0x14, 0x43, 0xa7,
	0x30, 0xe1, 0x19, 0xf6, 0x62, 0x6f, 0xbd, 0x48, 0x75, 0x85, 0x10, 0xcc, 0x14, 0xaf, 0x24, 0x9e,
	0x98, 0x8e, 0xa9, 0xd1, 0x05, 0xf8, 0x47, 0x5a, 0xc8, 0x1a, 0x4f, 0x4d, 0xd3, 0x0a, 0x74, 0x09,
	0x81, 0xe2, 0x4c, 0x64, 0x14, 0xcf, 0x4c, 0xdb, 0x29, 0x84, 0x21, 0xcc, 0xf4, 0xef, 0xb8, 0x90,
	0xd8, 0x37, 0x46, 0x2f, 0x51, 0x0c, 0xcb, 0x4a, 0xc7, 0xac, 0xb9, 0xa2, 0xfa, 0x83, 0x03, 0xe3,
	0x8e, 0x5b, 0x09, 0x81, 0xb9, 0x0b, 0xd6, 0xa0, 0x04, 0xc2, 0xca, 0xd6, 0x3a, 0xde, 0x74, 0xbd,
	0xdc, 0xce, 0x89, 0xf3, 0xd2, 0xde, 0x48, 0xae, 0x61, 0x91, 0xb2, 0xa6, 0x6a, 0xbb, 0xf5, 0xba,
	0x98, 0x4c, 0x1c, 0xf5, 0xc3, 0x76, 0x1b, 0x2b, 0x92, 0x18, 0x82, 0x9d, 0x76, 0x33, 0xd9, 0x05,
	0x66, 0xa6, 0x72, 0x03, 0x4e, 0x25, 0xdf, 0x1e, 0x9c, 0xd8, 0x91, 0x7b, 0x5a, 0x72, 0x29, 0xfe,
	0xcf, 0xc4, 0x1f, 0x31, 0xd1, 0xbb, 0xe4, 0x4c, 0xf4, 0x4c, 0xac, 0xfa, 0x83, 0x49, 0x04, 0x73,
	0x2e, 0x14, 0x13, 0x4a, 0x36, 0x06, 0x88, 0x9f, 0x0e, 0x1a, 0xdd, 0x82, 0x7f, 0x60, 0x6f, 0xef,
	0x14, 0x87, 0xda, 0x58, 0x6e, 0x23, 0x62, 0x0f, 0x4b, 0xfa, 0xc3, 0x92, 0xd7, 0xfe, 0xb0, 0xa9,
	0x1d, 0xdc, 0x7e, 0x7a, 0xb0, 0xda, 0x75, 0x6b, 0x0f, 0x14, 0x63, 0x08, 0x1f, 0x98, 0x7a, 0xe2,
	0x8d, 0x42, 0x8b, 0x9e, 0x5f, 0x13, 0x01, 0xf9, 0xc5, 0xa6, 0xaf, 0xf2, 0xc2, 0xf2, 0x96, 0x97,
	0xbc, 0xfb, 0x2b, 0x1a, 0x28, 0x47, 0x21, 0x71, 0xe0, 0x6e, 0xe0, 0xec, 0x51, 0x3f, 0xa0, 0x77,
	0xa1, 0x85, 0x43, 0xb4, 0x22, 0x63, 0x62, 0xe3, 0xf7, 0xf6, 0x81, 0x89, 0x77, 0xf7, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x27, 0x9a, 0x58, 0x35, 0x9a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EnvioPaquetesClient is the client API for EnvioPaquetes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EnvioPaquetesClient interface {
	GetList(ctx context.Context, in *Paquetes, opts ...grpc.CallOption) (*Respuesta, error)
	Seguimiento(ctx context.Context, in *Paquete, opts ...grpc.CallOption) (*Estado, error)
	HistorialCamion(ctx context.Context, in *EstadoCamion, opts ...grpc.CallOption) (*Respuesta, error)
}

type envioPaquetesClient struct {
	cc grpc.ClientConnInterface
}

func NewEnvioPaquetesClient(cc grpc.ClientConnInterface) EnvioPaquetesClient {
	return &envioPaquetesClient{cc}
}

func (c *envioPaquetesClient) GetList(ctx context.Context, in *Paquetes, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/EnvioPaquetes/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envioPaquetesClient) Seguimiento(ctx context.Context, in *Paquete, opts ...grpc.CallOption) (*Estado, error) {
	out := new(Estado)
	err := c.cc.Invoke(ctx, "/EnvioPaquetes/Seguimiento", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envioPaquetesClient) HistorialCamion(ctx context.Context, in *EstadoCamion, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/EnvioPaquetes/HistorialCamion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvioPaquetesServer is the server API for EnvioPaquetes service.
type EnvioPaquetesServer interface {
	GetList(context.Context, *Paquetes) (*Respuesta, error)
	Seguimiento(context.Context, *Paquete) (*Estado, error)
	HistorialCamion(context.Context, *EstadoCamion) (*Respuesta, error)
}

// UnimplementedEnvioPaquetesServer can be embedded to have forward compatible implementations.
type UnimplementedEnvioPaquetesServer struct {
}

func (*UnimplementedEnvioPaquetesServer) GetList(ctx context.Context, req *Paquetes) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedEnvioPaquetesServer) Seguimiento(ctx context.Context, req *Paquete) (*Estado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Seguimiento not implemented")
}
func (*UnimplementedEnvioPaquetesServer) HistorialCamion(ctx context.Context, req *EstadoCamion) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistorialCamion not implemented")
}

func RegisterEnvioPaquetesServer(s *grpc.Server, srv EnvioPaquetesServer) {
	s.RegisterService(&_EnvioPaquetes_serviceDesc, srv)
}

func _EnvioPaquetes_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Paquetes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvioPaquetesServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EnvioPaquetes/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvioPaquetesServer).GetList(ctx, req.(*Paquetes))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvioPaquetes_Seguimiento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Paquete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvioPaquetesServer).Seguimiento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EnvioPaquetes/Seguimiento",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvioPaquetesServer).Seguimiento(ctx, req.(*Paquete))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvioPaquetes_HistorialCamion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstadoCamion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvioPaquetesServer).HistorialCamion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EnvioPaquetes/HistorialCamion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvioPaquetesServer).HistorialCamion(ctx, req.(*EstadoCamion))
	}
	return interceptor(ctx, in, info, handler)
}

var _EnvioPaquetes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EnvioPaquetes",
	HandlerType: (*EnvioPaquetesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _EnvioPaquetes_GetList_Handler,
		},
		{
			MethodName: "Seguimiento",
			Handler:    _EnvioPaquetes_Seguimiento_Handler,
		},
		{
			MethodName: "HistorialCamion",
			Handler:    _EnvioPaquetes_HistorialCamion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "laboratorio.proto",
}
